import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";

const repositoryRoot = resolve(import.meta.dirname, "..");
const securityHeaders = [
  "X-Content-Type-Options",
  "Referrer-Policy",
  "Cross-Origin-Opener-Policy",
  "Cross-Origin-Embedder-Policy",
  "Cross-Origin-Resource-Policy",
  "Content-Security-Policy",
];

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

test("the standalone reverse proxy emits one copy of each security header", async () => {
  const config = await readFile(
    resolve(repositoryRoot, "deployment", "nginx-freekill.conf"),
    "utf8",
  );

  for (const header of securityHeaders) {
    const escaped = escapeRegExp(header);
    assert.match(config, new RegExp(`\\bproxy_hide_header\\s+${escaped};`, "i"));
    assert.equal(
      [...config.matchAll(new RegExp(`\\badd_header\\s+${escaped}\\b`, "gi"))].length,
      1,
      `${header} must be added exactly once`,
    );
  }
});

test("the standalone reverse proxy accepts the direct WebSocket hostname", async () => {
  const config = await readFile(
    resolve(repositoryRoot, "deployment", "nginx-freekill.conf"),
    "utf8",
  );

  assert.equal(
    [
      ...config.matchAll(
        /\bserver_name\s+zijing\.yejiaxin\.online\s+ws\.zijing\.yejiaxin\.online;/g,
      ),
    ].length,
    2,
    "both the HTTP redirect and HTTPS server must accept the direct WSS host",
  );
});

test("the reverse proxies allow the Qt WebAssembly binding runtime", async () => {
  for (const filename of ["nginx.conf", "nginx-freekill.conf"]) {
    const config = await readFile(
      resolve(repositoryRoot, "deployment", filename),
      "utf8",
    );

    assert.match(
      config,
      /\bscript-src\s+'self'\s+'unsafe-eval'\s+'wasm-unsafe-eval'/,
      `${filename} must permit the dynamic functions generated by Qt/Emscripten`,
    );
  }
});

test("the container serves content-addressed assets with one-month immutable caching", async () => {
  const config = await readFile(
    resolve(repositoryRoot, "deployment", "nginx.conf"),
    "utf8",
  );

  assert.match(config, /location \^~ \/\.freekill-assets\//);
  assert.match(config, /Cache-Control "public, max-age=2592000, immutable"/);
});
